//CreateUser
POST http://localhost:5000/users
{
    "username":"admin",
    "email": "admin@gmail.com",
    "password": "admin"
}

###
//Login Admin
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin"
}